sudo: required
language: java
jdk:
  - oraclejdk7
before_install:
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.site.skip=true -B -V -q
script:
  - mvn test -Punit
  - mvn integration-test -Pintegration,portal.test.vagrant
services:
  - docker
cache:
  directories:
    - $HOME/.m2
