version: '2'
services:
  db:
    image: ${DOCKER_REGISTRY}db:latest
    env_file:
      - src/main/resources/docker/env/common.env
      - src/main/resources/docker/env/portal.env
    volumes:
      - portal_data:/var/lib/mysql
    ports:
      - "13306:3306"
  portal:
    image: ${DOCKER_REGISTRY}portal:latest
    env_file:
      - src/main/resources/docker/env/common.env
    links:
      - db
      - geoserver
      - solr
    volumes:
      - ./emonocot-portal/target/emonocot-portal.war:/usr/local/tomcat/webapps/ROOT.war

  harvester:
    image: ${DOCKER_REGISTRY}harvester:latest
    env_file:
      - src/main/resources/docker/env/common.env
    links:
      - db
      - geoserver
      - solr
    volumes:
      - ./emonocot-harvest/target/emonocot-harvest.war:/usr/local/tomcat/webapps/harvester.war

  apache:
    image: ${DOCKER_REGISTRY}apache:latest
    env_file:
      - src/main/resources/docker/env/common.env
    links:
      - geoserver
      - harvester
      - portal
    volumes:
      - ./emonocot-portal/src/main/frontend/dist/css:/usr/local/apache2/htdocs/css
      - ./emonocot-portal/src/main/frontend/dist/fonts:/usr/local/apache2/htdocs/fonts
      - ./emonocot-portal/src/main/frontend/dist/img:/usr/local/apache2/htdocs/img
      - ./emonocot-portal/src/main/frontend/dist/js:/usr/local/apache2/htdocs/js
      - ./emonocot-static/src/main/tiles/:/usr/local/apache2/htdocs/tiles
    ports:
      - "10080:80"
    mem_limit: 200M

  solr:
    image: ${DOCKER_REGISTRY}solr:latest
    ports:
      - "18983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/powop/data

  geoserver:
    image: ${DOCKER_REGISTRY}geoserver:latest
    env_file: src/main/resources/docker/env/common.env
    links:
      - geodb
    ports:
      - "18080:8080"
    mem_limit: 1G

  geodb:
    image: ${DOCKER_REGISTRY}geodb:latest
    env_file:
      - src/main/resources/docker/env/common.env
      - src/main/resources/docker/env/geoserver.env


volumes:
  portal_data: {}
  solr_data: {}
